kind: ConfigMap
apiVersion: v1
data:
  DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
  DATABASE_FORMAT_SQL: "false"
  DATABASE_SHOW_SQL: "false"
  DATABASE_URL: jdbc:mysql://80.211.73.239:3306/c_base
  DATABASE_USER: aegisxdb
metadata:
  name: coll-backend-bebatch-configmap
  namespace: default
