apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque  
data:
  JWT_SECRET: "NzNmYzE3NzdiMDJjMGE3ZjJiZGQ2YjRmNTA4MGEyMzg2NWU5MGM2YWYyZmYzZjYxYjc0YWM1ZmI4OThmZmVmZDcwYzQ0ODUyNThkZjU1OTY4ZTE1YjE1MDkwNTNlMDY3YzA0NjhiZjhhOGFhYThmOTA5MTQ5NTE0MmNmYjZjMTExMjU4MjY2NjM2OGIwNGRiYjg0YmQ5OTE1NDc2MmUxYTVjZmRmMDZhYzQxMjRhNzJiMDVmYWZiYjNjZjNkYTE0YmVlODQyOTc2MmUzN2ExNzFiMGQ1NjZkMjA3YTkwMTY0ZjQwODM4YjkyM2Y3OTlhOTA0ZmFkZDI0NWFkYjIyZDQzZDYxNzM5ZDRkZDAzYzRhMTQ1Y2NiNDMzMTFmZTZlNzE1NDk1M2U0NTFiYTYyYWMyYWYxZmEzYjI4NmNlNDMwMDNlNjc2ODkzZDdhZjI3M2QwOGIwNzZiMWE4M2RjYTE5YWI0N2VmOTRkMDJhM2JmMTlhODg5NjhmODdkYzg3OTBkM2VmNWFkOTQxODU1ZTM0MDFlMGZjYmY1NDFjNTUwMDdhYzc3ZjZlMTUyMWJlMTJkMjA0YTQxYTZiNTI0ZWZiMGRmYTYxYjA2OWVkM2I2NWI1NjkwNzFiNjU0ZTBiYmVkM2VjMDgwYzI5NjVkMTMxZTBjZjJjY2U3NjQ2N2Y=" 